version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install --user JEDatabase
          name: pip JEDatabase
      - run:
          command: pip install --user JELogSystem
          name: pip JELogSystem
      - run:
          command: python Test/CreateTestDatabase.py
          name: Test
      - run:
          command: python Test/UnitTest.py
          name: UnitTest
      - run:
          command: python Test/TestControl.py
          name: TestControl

workflows:
  version: 2
  main:
    jobs:
      - build-and-test
